name: money_counter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.7.0
  responsive_framework: ^1.4.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/
